# POSTGRESQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciamento_curso
spring.datasource.username=postgres
spring.datasource.password=Loathe
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true